"""The 68 coined terms: definition (from context/COINED-TERMS-REVIEW.md, as
ontology/oht.ttl is not in this repository), triage group, job keywords for
the shortlist, and leads from the two earlier reviews (to be verified, not trusted)."""
# group: M = mechanical (note/date/type slot), P = pattern a standard models, D = domain or editorial
T = [
 (1,"oht:Record","class","a named graph holding one library record; the library's statements are made about this IRI","P","catalog record metadata record registration entry describing resource","dcat:CatalogRecord foaf:primaryTopic dcat:record prov:Entity dcat:Dataset"),
 (2,"oht:Version","class","one published release of a taxonomy; concept IRIs stay stable across versions","P","version release edition previous version lineage","dcat:version dcat:previousVersion dcat:hasVersion dcat:isVersionOf dcat:hasCurrentVersion adms:versionNotes pav:version owl:versionInfo schema:version dcat:DatasetSeries adms:Asset"),
 (3,"oht:Change","class","one change a version made (added, removed, renamed, moved and so on)","P","change delta difference revision changelog update","sh:SchemeDelta skos:changeNote prov:Activity prov:Revision schema:UpdateAction"),
 (4,"oht:Axis","class","a classification dimension other than the hierarchy, as a small concept scheme of values","P","dimension facet axis code list classification level","skos:ConceptScheme qb:DimensionProperty qb:codeList xkos:ClassificationLevel skos:Collection schema:DefinedTermSet"),
 (5,"oht:OutputSpec","class","how a classifier reports a concept (boolean, probability, ordinal, score)","P","output result procedure model prediction","ssn:Output ssn:hasOutput sosa:Procedure mls:Model mls:Implementation schema:PropertyValueSpecification qb:MeasureProperty"),
 (6,"oht:Uptake","class","one piece of evidence that someone uses the scheme (regulatory citation, platform adoption, benchmark use)","P","usage use adoption used by citation reference","duv:Usage duv:hasUsage nkos:usedBy dcterms:isReferencedBy"),
 (7,"oht:NoMatch","class","a mapping association asserting that its source concept has no counterpart in the target scheme","P","no match not found mapping cardinality absent counterpart","sssom:NoTermFound xkos:ConceptAssociation"),
 (8,"oht:OpenQuestion","class","an unresolved editorial point about a record, with a status and later a resolution","P","question questioning annotation motivation issue reply","oa:Annotation oa:questioning oa:replying oa:motivatedBy skos:editorialNote schema:Question adms:status"),
 (9,"oht:HumanReview","class","a person's review of a record","P","review assessing curation check activity","prov:Activity oa:assessing oa:moderating schema:Review dqv:QualityAnnotation"),
 (10,"oht:Session","class","a drafting session with a language model, as an activity, and the transcript it produced","P","conversation session activity software agent transcript message","prov:Activity schema:Conversation prov:SoftwareAgent schema:CreateAction schema:Message"),
 (11,"oht:family","property","what kind of scheme this is (harm taxonomy and so on)","M","type kind of knowledge organization system genre","dcterms:type schema:additionalType nkostype:taxonomy"),
 (12,"oht:classifies","property","the kind of unit a scheme sorts, such as a harm or a content item","D","unit of analysis covers subject classified unit","disco:analysisUnit xkos:covers dcterms:subject"),
 (13,"oht:purpose","property","what the issuer says the scheme is for","M","purpose intended use aim description","dcterms:description dcterms:abstract"),
 (14,"oht:legalStatus","property","legal force of the scheme: statutory, guidance, voluntary, commercial, academic","D","legal status force binding in force","adms:status eli:in_force"),
 (15,"oht:statusDate","property","when the current adms:status began","M","status date date modified valid","dcterms:date dcterms:modified dcterms:valid"),
 (16,"oht:sunsetDate","property","the announced date after which a scheme or service ceases","M","expires end date no longer available ceases","schema:expires dcterms:valid schema:endDate eli:date_no_longer_in_force"),
 (17,"oht:severityEncoding","property","where severity lives in a scheme: nowhere, in the hierarchy, on an axis, both","D","severity encoding","skos:note"),
 (18,"oht:hasConcept","property","links a concept scheme to each concept in it (inverse of skos:inScheme)","P","has concept defined term in scheme member","schema:hasDefinedTerm skos:inScheme skos:hasTopConcept dcterms:hasPart skos:member"),
 (19,"oht:primarySource","property","the authoritative text that defines the scheme","P","primary source authority cites as authority","prov:hadPrimarySource cito:citesAsAuthority dcterms:source"),
 (20,"oht:sourceType","property","primary, secondary or tertiary source, relative to the citing scheme","M","source type primary secondary","prov:hadPrimarySource prov:wasDerivedFrom"),
 (21,"oht:hasChange","property","a version lists a change","M","has change part","dcterms:hasPart"),
 (22,"oht:changeType","property","added, removed, renamed, redefined, moved, merged, split, reclassified","M","change type kind of change","dcterms:type"),
 (23,"oht:affectsConcept","property","the concept a change touched","P","affects concept target subject changed","dcterms:subject prov:used oa:hasTarget"),
 (24,"oht:officialMapping","property","the issuer's own crosswalk from the previous version","P","correspondence mapping crosswalk","xkos:Correspondence dcterms:relation"),
 (25,"oht:introducedIn","property","the version in which a concept first appeared","P","introduced first version created in","prov:generatedAtTime dcterms:issued pav:createdAt"),
 (26,"oht:retiredIn","property","the version in which a concept was removed; the IRI remains","P","retired deprecated obsolete removed replaced","owl:deprecated prov:invalidatedAtTime dcterms:isReplacedBy schema:supersededBy"),
 (27,"oht:hasAxis","property","a scheme declares an axis","M","has axis dimension component part","dcterms:hasPart qb:component"),
 (28,"oht:axisKind","property","whether an axis is ordinal or categorical","M","axis kind ordinal categorical scale","dcterms:type"),
 (29,"oht:multiValued","property","whether a concept may take several values on the axis","D","multi valued cardinality","owl:FunctionalProperty"),
 (30,"oht:hasFacetValue","property","a concept takes a value from one of its scheme's axes","D","facet value dimension value classification","skos:related"),
 (31,"oht:consequence","property","what follows from a concept or value in the scheme (a note users filter on)","M","consequence note scope note","skos:note skos:scopeNote"),
 (32,"oht:hasOutput","property","attaches an output specification to a scheme or classifier","P","has output","ssn:hasOutput"),
 (33,"oht:outputType","property","boolean, probability, ordinal, score or none","M","output type kind","dcterms:type"),
 (34,"oht:outputAxis","property","for ordinal outputs, the axis returned","D","output scale axis","qb:dimension"),
 (35,"oht:modality","property","the kind of input a concept applies to (text, image, audio, video)","D","modality media type format input","dcterms:format dcterms:medium schema:encodingFormat"),
 (36,"oht:legalBasis","property","the legal provision behind a concept, as an ELI legal resource","D","legal basis based on implements law provision","eli:based_on eli:implements dcterms:source dpv:hasLegalBasis"),
 (37,"oht:contextDependent","property","the scheme says the concept's status depends on deployment context","D","context dependent","skos:note"),
 (38,"oht:verbatim","property","on an explanatory note, whether the text is the source's exact words","P","verbatim quotation quoted from exact words","prov:Quotation prov:wasQuotedFrom cito:includesQuotationFrom"),
 (39,"oht:operationalises","property","this scheme turns the target's duties or principles into practice","D","operationalises implements transposes conforms to","eli:implements eli:transposes dcterms:conformsTo"),
 (40,"oht:operationalisedBy","property","inverse of operationalises","D","implemented by operationalised by","eli:implemented_by eli:transposed_by"),
 (41,"oht:conflictsWith","property","two schemes make incompatible claims about the same field","D","conflicts disagrees disjoint incompatible","xkos:disjoint owl:disjointWith cito:disagreesWith"),
 (42,"oht:hasUptake","property","attaches uptake evidence to a scheme","P","has usage uptake","duv:hasUsage"),
 (43,"oht:uptakeKind","property","regulatory citation, platform adoption, benchmark use and so on","M","uptake kind type","dcterms:type"),
 (44,"oht:strength","property","strong, moderate, weak, as the library judges evidence","D","strength confidence quality evidence","sssom:confidence dqv:QualityAnnotation"),
 (45,"oht:mappingRelation","property","the relation an association asserts, including no_match","P","mapping predicate relation match","sssom:predicate_id sssom:predicate_modifier skos:closeMatch skos:exactMatch"),
 (46,"oht:confidence","property","issuer_asserted, high, medium, low - categorical confidence in a mapping","P","confidence mapping provider","sssom:confidence sssom:mapping_provider"),
 (47,"oht:score","property","numeric confidence 0 to 1","P","confidence score similarity score","sssom:confidence sssom:similarity_score"),
 (48,"oht:method","property","how a record or crosswalk was produced","P","mapping justification method generated by curation","sssom:mapping_justification semapv:ManualMappingCuration prov:wasGeneratedBy"),
 (49,"oht:derivationMethod","property","how an item relates to its source: authored, verbatim, transcribed, paraphrased, translated, converted, inferred, llm_drafted, mixed","D","derivation digital source type quotation revision translation","prov:Quotation prov:Revision prov:PrimarySource iptcdst:trainedAlgorithmicMedia"),
 (50,"oht:reviewed","property","a person has checked this item against its source","M","reviewed checked","prov:used"),
 (51,"oht:verification","property","verified_primary, secondary_only, unverified","D","verification verified","dqv:QualityAnnotation"),
 (52,"oht:reviewDue","property","when the record should next be checked","D","review due next review date","schema:expires schema:lastReviewed"),
 (53,"oht:inclusion","property","why the library holds the record: core, comparator, adjacent, context","D","inclusion reason","skos:editorialNote"),
 (54,"oht:humanReview","property","summary on the record of the review status in its bundle","M","human review status","dcterms:type"),
 (55,"oht:hasOpenQuestion","property","attaches an open question to a record","P","has annotation target","oa:hasTarget"),
 (56,"oht:resolution","property","how an open question was resolved","M","resolution history note reply","skos:historyNote oa:replying dcterms:description"),
 (57,"oht:release","property","the library release label in which a record state was published","P","release version label","dcat:version pav:version owl:versionInfo"),
 (58,"oht:redistributable","property","whether the archived copy may be republished","P","access rights redistribution rights license","dcterms:accessRights dcterms:license odrl:distribute"),
 (59,"oht:redactions","property","for a published derived copy, what was removed and kept","M","redaction provenance changes statement","dcterms:provenance"),
 (60,"oht:hasHumanReview","property","attaches the review to a record","M","has review","prov:used schema:review"),
 (61,"oht:reviewStatus","property","none, sampled, full, on the review","M","review status type","dcterms:type"),
 (62,"oht:toolPath","property","where a tool lives in the repository","M","repository path code location","schema:codeRepository dcterms:identifier doap:repository"),
 (63,"oht:commit","property","the git commit of a run or change","M","commit revision identifier","doap:revision dcterms:identifier"),
 (64,"oht:session","property","links a model agent to its session","P","associated with session agent","prov:wasAssociatedWith"),
 (65,"oht:archiveStatus","property","not_archived, private, public","M","archive status access rights","dcterms:accessRights"),
 (66,"oht:transcript","property","the archived full transcript of a session","P","generated transcript","prov:generated"),
 (67,"oht:excerpt","property","the published redacted excerpt of a transcript","P","excerpt part derived","prov:generated dcterms:hasPart prov:wasDerivedFrom"),
 (68,"oht:locator","property","where in the transcript the agent's work is","P","locator location in document part","bibo:locator"),
]
