"""Plan steps D and E: judgements for each coined term.

fit: exact | super (fits as superclass or superproperty) | related | irrelevant
verdict: Keep | Keep under standard super | Replace | Drop
cmp: comparison with context/review-so-far.md (items 1-20 only)
Definitions are not typed here: report.py quotes them from index/terms.csv,
except where the machine-readable file has none (QUOTES below).
"""

# Quotes from specification text, for terms whose RDF carries no definition.
QUOTES = {
    "http://www.w3.org/ns/prov#generated": ("Generation is the completion of production of a new entity by an activity. [prov:generated is listed as the inverse of prov:wasGeneratedBy in DCAT 3, section 7]", "https://www.w3.org/TR/prov-o/#Generation ; https://www.w3.org/TR/vocab-dcat-3/#inverse-properties"),
    "http://rdf-vocabulary.ddialliance.org/xkos#classifiedUnder": ("classifying results in the creation of a RDF statement where the resource representing the entity is the subject and the concept representing the classification item is the object. XKOS defines a generic property, xkos:classifiedUnder, that can be used in such statements ... it is expected that xkos:classifiedUnder will be specialized for different classification systems.", "https://rdf-vocabulary.ddialliance.org/xkos.html (section 5)"),
    "http://rdf-vocabulary.ddialliance.org/xkos#covers": ("A classification covers a defined field: economic activity, occupations, living organisms, etc. ... The field covered should be represented by a skos:Concept", "https://rdf-vocabulary.ddialliance.org/xkos.html (section 5)"),
    "http://rdf-vocabulary.ddialliance.org/xkos#Correspondence": ("The complete collection of such associations for all the concepts in two SKOS Concept Schemes forms a correspondence and is expressed as an instance of the xkos:Correspondence class.", "https://rdf-vocabulary.ddialliance.org/xkos.html (section 7)"),
    "http://rdf-vocabulary.ddialliance.org/xkos#ConceptAssociation": ("XKOS defines the xkos:ConceptAssociation class that can be used to represent correspondences between classification items when the SKOS properties are not sufficient.", "https://rdf-vocabulary.ddialliance.org/xkos.html (section 7)"),
    "http://www.w3.org/ns/dcat#isVersionOf": ("properties dcat:isVersionOf, dcat:next, and dcterms:isReplacedBy have been removed from 6. Vocabulary specification [it survives only in the informative table of inverses and in section 11 prose]", "https://www.w3.org/TR/vocab-dcat-3/ (Appendix, changes since the second public working draft)"),
    "http://publications.europa.eu/resource/authority/access-right/PUBLIC": ("access status for resources that are publicly accessible", "http://publications.europa.eu/resource/authority/access-right/PUBLIC (dereferenced concept)"),
    "http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC": ("access status for resources that are not publicly accessible for privacy, security or other reasons", "http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC (dereferenced concept)"),
    "owl:annotatedProperty": ("predicate_id: The ID of the predicate or relation that relates the subject and object of this match. [SSSOM serialises this slot as owl:annotatedProperty]", "https://w3id.org/sssom/ (LinkML schema, slot predicate_id)"),
}

D = "http://purl.org/dc/terms/"
S = "http://www.w3.org/2004/02/skos/core#"
P = "http://www.w3.org/ns/prov#"
SC = "https://schema.org/"
SS = "https://w3id.org/sssom/"
OA = "http://www.w3.org/ns/oa#"
DCAT = "http://www.w3.org/ns/dcat#"
X = "http://rdf-vocabulary.ddialliance.org/xkos#"

J = {
1: dict(verdict="Replace", line="Use dcat:CatalogRecord, with foaf:primaryTopic pointing at the scheme; the named graph can carry the record's IRI.",
  cands=[(DCAT+"CatalogRecord","exact","A record describing the registration of one resource in a catalogue is exactly what the library's record is; the named-graph mechanism is an implementation choice DCAT does not forbid."),
         ("http://xmlns.com/foaf/0.1/primaryTopic","exact","DCAT-AP 3 makes foaf:primaryTopic mandatory on a catalogue record (along with dcterms:modified), so portals expect it."),
         (P+"Entity","super","True but too general to help consumers."),
         (DCAT+"Dataset","related","Describes the scheme itself, not the library's record about it.")],
  cmp="Agrees with the second review (Replace). The first review's objection that DCAT cannot distinguish 'a graph the library curates' is answered by dcat:CatalogRecord itself. If SHACL needs its own target class, declare oht:Record rdfs:subClassOf dcat:CatalogRecord."),
2: dict(verdict="Replace", line="Use DCAT 3 versioning: dcat:hasVersion from the abstract scheme, dcat:version for the label, dcat:previousVersion for the chain, dcat:hasCurrentVersion for the latest.",
  cands=[(DCAT+"hasVersion","exact","Links the stable, version-independent scheme to each release, which is the oht:Version pattern."),
         (DCAT+"version","exact","The release label (\"2023\"); DCAT-AP 3 names it on dcat:Dataset."),
         (DCAT+"previousVersion","exact","Version chain."),
         (DCAT+"hasCurrentVersion","exact","Points at the latest release."),
         (DCAT+"isVersionOf","related","Removed from the DCAT 3 vocabulary specification; only listed as an informative inverse. Use dcterms:isVersionOf if a back link is stored."),
         (D+"isVersionOf","super","The standard back link from a version to the work."),
         ("http://www.w3.org/ns/adms#versionNotes","related","Change notes between versions; useful alongside, SEMIC ADMS 2.0."),
         ("http://purl.org/pav/version","related","Same idea as dcat:version, tier 2; prefer DCAT.")],
  cmp="Agrees with the second review (Replace) except on dcat:isVersionOf, which DCAT 3 removed from its vocabulary specification (appendix of changes); the second review lists it as a DCAT 3 term. DCAT 3 has no Version class: versions are ordinary resources, so if a class is needed for SHACL, subclass dcat:Resource or dcat:Dataset."),
3: dict(verdict="Keep", line="No standard class for one change in a changelog; cite skos-history as prior art.",
  cands=[("http://purl.org/skos-history/SchemeDelta","related","A whole delta between two scheme versions, not one change; tier 3."),
         (P+"Revision","related","A qualified derivation between two entity versions, not a changelog entry."),
         (SC+"UpdateAction","related","An action (activity); typing issuer changelog entries as activities mixes them with the library's own provenance, as the first review argued."),
         (S+"changeNote","related","Free-text note; could carry a human-readable summary of the change.")],
  cmp="Agrees with both reviews (Keep, skos-history as prior art)."),
4: dict(verdict="Keep under standard super", line="Declare oht:Axis rdfs:subClassOf skos:ConceptScheme.",
  cands=[(S+"ConceptScheme","super","An axis is a small set of values, which is a concept scheme; SKOS tools then read axes."),
         ("http://purl.org/linked-data/cube#DimensionProperty","related","Analogue from statistics: a dimension with a code list; it is a property class, not a scheme."),
         (X+"ClassificationLevel","related","Levels of one hierarchy, not orthogonal dimensions."),
         (SC+"DefinedTermSet","super","schema.org's 'set of categories or a classification scheme'; optional extra alignment for web consumers.")],
  cmp="Agrees with the second review. qb:DimensionProperty is now verified at source (it was memory)."),
5: dict(verdict="Keep under standard super", line="Declare oht:OutputSpec rdfs:subClassOf ssn:Output, with the classifier typed sosa:Procedure.",
  cands=[("http://www.w3.org/ns/ssn/Output","super","In SSN, Output describes what a Procedure reports; an output specification is a kind of that. The coined class adds the output type and axis."),
         ("http://www.w3.org/ns/sosa/Procedure","exact","SOSA's Procedure explicitly includes algorithms and computational methods, so a classifier fits."),
         ("http://www.w3.org/ns/mls#Model","related","ML Schema models are outputs of runs, not descriptions of a model's output format."),
         (SC+"PropertyValueSpecification","related","Constraints on form inputs.")],
  cmp="Partly agrees with the second review: same vocabulary, but I propose a subclass rather than outright replacement, because ssn:Output alone does not say boolean versus probability versus ordinal. This also moves the output onto the classifier, as the second review said."),
6: dict(verdict="Keep", line="duv:Usage is usage guidance, not evidence of use; keep oht:Uptake, and optionally assert nkos:usedBy for the simple case.",
  cands=[("http://www.w3.org/ns/duv#Usage","related","Defined as 'a helpful description of actions that can be performed on a given dataset': instructions, not evidence that someone used it."),
         ("http://w3id.org/nkos#usedBy","related","'Agent using the described KOS' covers who uses a scheme, not the evidence or its strength; tier 3 and its namespace no longer resolves."),
         (D+"isReferencedBy","super","Fits only the regulatory-citation kind of uptake."),
         ("http://purl.org/spar/cito/Citation","related","Citations are one kind of uptake.")],
  cmp="Disagrees with the second review, which proposed a subclass of duv:Usage while noting its definitions 'lean towards usage guidance'. Read at source, DUV's Usage is guidance for users, so subclassing would misstate what an Uptake is. NKOS usedBy, unchecked in the second review, is now read: it names the agent only."),
7: dict(verdict="Replace", line="Follow SSSOM: use sssom:NoTermFound as the object (with the target scheme as object_source), rather than a marker class.",
  cands=[(SS+"NoTermFound","exact","SSSOM's own convention for 'the corresponding entity could not be found'."),
         (SS+"mapping_cardinality_enum#1:0","exact","Alternative SSSOM route: 'the subject has no match in the object vocabulary'."),
         (SS+"NegatedPredicate","related","Negates one specific mapping (A is not a close match of B); different from 'no counterpart at all'."),
         (X+"ConceptAssociation","related","An association with no target cannot be told apart from an omission, as the first review said.")],
  cmp="Agrees with the second review (Replace). Now verified from the SSSOM schema itself, and SSSOM also offers the 1:0 mapping cardinality value. Also agrees that it duplicates the no_match value of item 45."),
8: dict(verdict="Replace", line="Use oa:Annotation with oa:motivatedBy oa:questioning targeting the record; the resolution is a reply annotation (oa:replying); keep adms:status for open or closed.",
  cands=[(OA+"Annotation","exact","A Web Annotation about the record."),
         (OA+"questioning","exact","'The motivation for when the user intends to ask a question about the Target.'"),
         (OA+"replying","exact","Motivation for the annotation that resolves it."),
         ("http://www.w3.org/ns/adms#status","related","Workflow status; carries open/resolved."),
         (S+"editorialNote","related","No status or resolution."),
         (SC+"Question","related","Q&A web content.")],
  cmp="Agrees with the second review, and closes its caveat: oa:questioning and oa:replying are now verified directly in the W3C Web Annotation Vocabulary (oa.ttl), not via TEI."),
9: dict(verdict="Replace", line="Use prov:Activity with a dcterms:type value for review; if the review's outcome is recorded, an oa:Annotation motivated by oa:assessing is the standard shape.",
  cands=[(P+"Activity","super","A review is an activity."),
         (OA+"assessing","related","For recording the review's judgement as an annotation."),
         (SC+"Review","related","A review as a creative work (restaurant, film)."),
         ("http://www.w3.org/ns/dqv#QualityAnnotation","related","Quality feedback on a dataset; tier 2.")],
  cmp="Agrees with the second review (Replace). prov:Activity now verified. Its point that a review with status 'none' is a review that never happened stands."),
10: dict(verdict="Replace", line="prov:Activity with prov:wasAssociatedWith a prov:SoftwareAgent; type the transcript schema:Conversation.",
  cands=[(P+"Activity","super","The session as activity."),
         (P+"SoftwareAgent","exact","The model."),
         (SC+"Conversation","exact","The transcript; RO-Crate's context names schema:Conversation."),
         (SC+"CreateAction","related","RO-Crate precedent for a tool run; heavier than needed.")],
  cmp="Agrees with the second review."),
11: dict(verdict="Replace", line="Use dcterms:type with values from a local family scheme, aligned to NKOS KOS types (skos:closeMatch) rather than depending on them.",
  cands=[(D+"type","exact","'The nature or genre of the resource.'"),
         ("http://w3id.org/nkos/nkostype#taxonomy","related","Useful alignment target; tier 3, the namespace no longer resolves and the values exist only as an HTML list."),
         (SC+"additionalType","related","schema.org's equivalent slot; optional."),
         (DCAT+"themeTaxonomy","irrelevant","Names the KOS a catalogue uses, not a scheme's kind.")],
  cmp="Agrees with the second review on dcterms:type. Adds a caution: the NKOS KOS Types namespace now redirects to a workshop page, so depend on a local scheme and align to NKOS in a separate file (tier 3 rule)."),
12: dict(verdict="Keep", line="No standard property for the unit a scheme sorts; xkos:covers is the field, not the unit.",
  cands=[(X+"covers","related","The field a classification covers (online harms), which WEF and OpenAI share; the unit (harm versus content item) is what differs."),
         ("http://rdf-vocabulary.ddialliance.org/discovery#analysisUnit","related","Same idea for studies and variables; tier 3, domain Study/Variable."),
         (D+"subject","irrelevant","Topic.")],
  cmp="Agrees with both reviews (Keep; DDI analogue). xkos:covers now read at source."),
13: dict(verdict="Keep under standard super", line="Declare oht:purpose rdfs:subPropertyOf dcterms:description.",
  cands=[(D+"description","super","'An account of the resource'; generic tools will show purpose as description."),
         ("http://rdf-vocabulary.ddialliance.org/discovery#purpose","related","Purpose of a study; tier 3."),
         (D+"abstract","related","A summary, not a purpose.")],
  cmp="Agrees with the second review; now verified."),
14: dict(verdict="Keep", line="Legal force of a code or standard (statutory, guidance, voluntary) has no standard property; ELI's in_force is whether legislation is in force.",
  cands=[("http://data.europa.eu/eli/ontology#in_force","related","In force / not in force, for legal resources only."),
         (SC+"legislationLegalForce","related","Same as ELI's, for schema.org Legislation."),
         ("http://www.w3.org/ns/adms#status","irrelevant","Lifecycle status, orthogonal.")],
  cmp="Agrees with both reviews (Keep); the second review's advice to drop 'commercial' and 'academic' as publisher facts is outside term matching but sound."),
15: dict(verdict="Keep under standard super", line="Declare oht:statusDate rdfs:subPropertyOf dcterms:date.",
  cands=[(D+"date","super","'A point or period of time associated with an event in the lifecycle of the resource.'"),
         (D+"modified","related","Last content change; can differ from status change."),
         (D+"valid","related","Validity range.")],
  cmp="Agrees with the second review; the dcterms:date definition is now verified."),
16: dict(verdict="Replace", line="Use schema:expires for schemes; for services, keep a coined term under dcterms:date or accept the domain stretch.",
  cands=[(SC+"expires","exact","'Date the content expires and is no longer useful or available.' Its domain is CreativeWork (and Certification), which covers a scheme but not a service such as an API."),
         (D+"valid","related","A validity range; harder to query."),
         ("http://data.europa.eu/eli/ontology#date_no_longer_in_force","related","For legislation only."),
         (SC+"endDate","related","End of an event or period.")],
  cmp="Agrees with the second review (Replace), now verified, with one caveat it did not raise: schema:expires is declared on CreativeWork, and some sunset examples (Perspective API) are services."),
17: dict(verdict="Keep", line="A structural fact about the scheme with no standard home.",
  cands=[(S+"note","related","Prose; the value is structured and filtered on."),
         ("https://w3id.org/dpv/risk#HighSeverity","related","DPV has severity levels (values), not where severity is encoded.")],
  cmp="Agrees with the second review (Keep). DPV RISK severity levels could supply axis values, a separate question."),
18: dict(verdict="Drop", line="Use a JSON-LD @reverse of skos:inScheme; if a stored forward link is ever needed, schema:hasDefinedTerm.",
  cands=[(SC+"hasDefinedTerm","exact","'A Defined Term contained in this term set'; requires typing the scheme schema:DefinedTermSet. In current schema.org core (not pending); absent from LOV's 2020 copy."),
         (S+"inScheme","exact","The standard link, from concept to scheme."),
         (S+"hasTopConcept","related","Top concepts only.")],
  cmp="Agrees with the second review; schema:hasDefinedTerm now verified at source."),
19: dict(verdict="Replace", line="Use prov:hadPrimarySource, plus cito:citesAsAuthority to single out the authoritative text.",
  cands=[(P+"hadPrimarySource","exact","A source produced by an agent with direct knowledge; the issuer's PDF is that."),
         ("http://purl.org/spar/cito/citesAsAuthority","exact","'cites the cited entity as one that provides an authoritative description or definition'."),
         (D+"source","related","Any source the resource derives from.")],
  cmp="Agrees with both reviews."),
20: dict(verdict="Drop", line="Primary versus secondary belongs on the relation (prov:hadPrimarySource versus prov:wasDerivedFrom).",
  cands=[(P+"hadPrimarySource","exact","Primary case."),
         (P+"wasDerivedFrom","super","Everything else; RO-Crate names it.")],
  cmp="Agrees with the second review."),
21: dict(verdict="Keep under standard super", line="Declare oht:hasChange rdfs:subPropertyOf dcterms:hasPart.",
  cands=[(D+"hasPart","super","A change entry is logically part of the version's record."),
         ("http://purl.org/skos-history/hasDelta","related","Version to delta; tier 3.")], cmp=""),
22: dict(verdict="Replace", line="Use dcterms:type on the change; reuse IAO obsolescence reasons for merged and split where they fit.",
  cands=[(D+"type","exact","One type slot on a change."),
         ("http://purl.obolibrary.org/obo/IAO_0000227","related","Value alignment: 'terms merged'."),
         ("http://purl.obolibrary.org/obo/IAO_0000229","related","Value alignment: 'term split'."),
         (S+"changeNote","related","Prose.")], cmp=""),
23: dict(verdict="Keep", line="None of the standard 'target' properties has a changelog entry as its subject.",
  cands=[(D+"subject","related","Topic, odd for an operand."),
         (P+"used","related","Requires the change to be an activity (see item 3)."),
         (OA+"hasTarget","related","Domain oa:Annotation.")], cmp=""),
24: dict(verdict="Replace", line="Model the issuer's crosswalk as an xkos:Correspondence attributed to the issuer (dcterms:publisher), with the TSV as its source (prov:hadPrimarySource or a dcat:Distribution).",
  cands=[(X+"Correspondence","exact","A correspondence between two concept schemes, which the issuer's crosswalk is."),
         (D+"relation","super","Too vague to help.")], cmp=""),
25: dict(verdict="Keep", line="No standard 'first appeared in version' link; dcterms:created and prov:generatedAtTime are dates, not issuer versions.",
  cands=[(D+"created","related","Date."),
         (P+"generatedAtTime","related","Timestamp."),
         ("http://purl.org/pav/createdAt","irrelevant","Despite its name, PAV defines it as the geo-location of the creating agent.")], cmp=""),
26: dict(verdict="Keep", line="Keep the version link, and also assert owl:deprecated true and dcterms:isReplacedBy so generic tools see the retirement.",
  cands=[("http://www.w3.org/2002/07/owl#deprecated","related","A flag with no version; add it alongside."),
         (D+"isReplacedBy","related","The successor, where there is one."),
         ("http://purl.obolibrary.org/obo/IAO_0100001","related","OBO's 'term replaced by'; tier 2."),
         (P+"invalidatedAtTime","related","Timestamp.")], cmp=""),
27: dict(verdict="Keep under standard super", line="Declare oht:hasAxis rdfs:subPropertyOf dcterms:hasPart.",
  cands=[(D+"hasPart","super","An axis is logically part of the scheme."),
         ("http://purl.org/linked-data/cube#component","related","Data Cube structure component; analogue only.")], cmp=""),
28: dict(verdict="Replace", line="Use dcterms:type on the axis with ordinal and categorical values.",
  cands=[(D+"type","exact","One type slot on an axis.")], cmp=""),
29: dict(verdict="Keep", line="schema:multipleValues says the same thing but only for form-input specifications.",
  cands=[(SC+"multipleValues","related","'Whether multiple values are allowed for the property'; domain PropertyValueSpecification."),
         ("http://www.w3.org/2002/07/owl#FunctionalProperty","related","Would need one property per axis.")], cmp=""),
30: dict(verdict="Keep under standard super", line="Declare oht:hasFacetValue rdfs:subPropertyOf xkos:classifiedUnder.",
  cands=[(X+"classifiedUnder","super","XKOS's generic 'entity classified under a classification item' property, which it expects to be specialised; a concept taking a value on an axis is exactly that."),
         (S+"related","related","Associative only.")], cmp=""),
31: dict(verdict="Keep under standard super", line="Declare oht:consequence rdfs:subPropertyOf skos:scopeNote (or skos:note).",
  cands=[(S+"scopeNote","super","'A note that helps to clarify the meaning and/or the use of a concept.'"),
         (S+"note","super","Safe general parent."),
         ("https://w3id.org/dpv#hasConsequence","related","Links to a dpv:Consequence resource, not a note.")], cmp=""),
32: dict(verdict="Replace", line="Use ssn:hasOutput from the classifier (sosa:Procedure), if item 5 is adopted.",
  cands=[("http://www.w3.org/ns/ssn/hasOutput","exact","'Relation between a Procedure and an Output of it.'"),
         ("http://www.w3.org/ns/mls#hasOutput","related","Run to model.")], cmp=""),
33: dict(verdict="Replace", line="Use dcterms:type on the output specification.",
  cands=[(D+"type","exact","One type slot on an output.")], cmp=""),
34: dict(verdict="Keep", line="No standard term for the scale a classifier's output is expressed on.",
  cands=[("http://purl.org/linked-data/cube#dimension","related","Data Cube structure, not classifier output.")], cmp=""),
35: dict(verdict="Keep", line="Keep the property (it describes what a concept applies to, not a resource's format), but take its values from the DCMI Type Vocabulary.",
  cands=[("http://purl.org/dc/dcmitype/Text","related","Value reuse: DCMI Type gives Text, StillImage, MovingImage, Sound; tier 1."),
         (D+"format","related","Format of the resource itself."),
         (SC+"encodingFormat","related","MIME type of a media object.")], cmp=""),
36: dict(verdict="Keep", line="DPV's legal basis is about justifying processing; ELI's links run between legal resources.",
  cands=[("https://w3id.org/dpv#hasLegalBasis","related","Range dpv:LegalBasis, 'used to justify processing of data or use of technology'."),
         ("http://data.europa.eu/eli/ontology#based_on","related","Work empowered by another; legal resources only."),
         ("http://data.europa.eu/eli/ontology#implements","irrelevant","Deprecated in current ELI: 'Use \"applies\" instead.'"),
         (D+"source","related","Already used for bibliographic sources.")], cmp=""),
37: dict(verdict="Keep", line="A boolean flag with no standard equivalent.",
  cands=[(S+"note","related","Prose.")], cmp=""),
38: dict(verdict="Replace", line="Express verbatim notes with prov:wasQuotedFrom from the note to its source; non-verbatim with prov:wasDerivedFrom. It also overlaps the 'verbatim' value of item 49.",
  cands=[(P+"wasQuotedFrom","exact","'An entity is derived from an original entity by copying, or quoting, some or all of it.'"),
         ("http://purl.org/spar/cito/includesQuotationFrom","related","Citation-level; for documents."),
         (OA+"exact","irrelevant","Text selector.")], cmp=""),
39: dict(verdict="Keep", line="No standard 'puts duties into practice' relation between non-legal schemes and law; dcterms:conformsTo is conformance, ELI's are between legal resources.",
  cands=[(D+"conformsTo","related","'An established standard to which the described resource conforms.'"),
         ("http://data.europa.eu/eli/ontology#applies","related","Informative conformity between legislation; range LegalResource."),
         ("http://data.europa.eu/eli/ontology#transposes","related","Binding, legislation to legislation."),
         ("http://data.europa.eu/eli/ontology#implements","irrelevant","Deprecated in current ELI.")], cmp=""),
40: dict(verdict="Drop", line="Same rule as item 18: express the inverse with JSON-LD @reverse, not a second stored property.",
  cands=[("http://data.europa.eu/eli/ontology#implemented_by","irrelevant","Deprecated in current ELI.")], cmp=""),
41: dict(verdict="Keep", line="cito:disagreesWith is a citing work disagreeing with a cited one; conflict here is the library's symmetric judgement.",
  cands=[("http://purl.org/spar/cito/disagreesWith","related","Directional and authored by the citing work."),
         (X+"disjoint","related","Concepts with no common instances."),
         ("http://www.w3.org/2002/07/owl#disjointWith","irrelevant","Classes.")], cmp=""),
42: dict(verdict="Keep", line="Follows item 6.",
  cands=[("http://www.w3.org/ns/duv#hasUsage","related","Usage guidance, see item 6.")], cmp=""),
43: dict(verdict="Replace", line="Use dcterms:type on the uptake.",
  cands=[(D+"type","exact","One type slot on an uptake.")], cmp=""),
44: dict(verdict="Keep", line="A categorical evidence grade; merge with item 46 into one scale as the first review suggested.",
  cands=[(SS+"confidence","related","Numeric, and about mappings."),
         (SC+"evidenceLevel","related","Medical guidelines only.")], cmp=""),
45: dict(verdict="Replace", line="Carry the relation as the SKOS mapping property itself (skos:exactMatch, closeMatch, broadMatch, narrowMatch, relatedMatch) in SSSOM's predicate slot, and drop no_match (item 7).",
  cands=[("owl:annotatedProperty","exact","SSSOM's predicate_id: the IRI of the relation."),
         (S+"closeMatch","exact","Value: the mapping relation is itself a standard IRI."),
         (S+"mappingRelation","super","Parent of the SKOS mapping properties."),
         (SS+"predicate_modifier","related","For negating a specific mapping.")], cmp=""),
46: dict(verdict="Keep", line="Keep the categorical value, but move 'issuer_asserted' out: who asserted a mapping is sssom:mapping_provider (or the justification), not a confidence level.",
  cands=[(SS+"confidence","related","Numeric 0 to 1; see item 47."),
         (SS+"mapping_provider","related","Carries the issuer_asserted case.")], cmp=""),
47: dict(verdict="Replace", line="Use sssom:confidence.",
  cands=[(SS+"confidence","exact","'the creator's confidence or estimated probability that the mapping record is correct', 0.0 to 1.0."),
         (SS+"similarity_score","related","Similarity, not correctness.")], cmp=""),
48: dict(verdict="Replace", line="For crosswalks, sssom:mapping_justification with SEMAPV values (manual curation, lexical matching, LLM-based matching); for records, prov:wasGeneratedBy an activity typed with dcterms:type.",
  cands=[(SS+"mapping_justification","exact","How a mapping was shown to be right."),
         ("https://w3id.org/semapv/vocab/ManualMappingCuration","exact","Value."),
         ("https://w3id.org/semapv/vocab/LLMBasedMatching","exact","Value for llm_assisted crosswalks."),
         (P+"wasGeneratedBy","exact","For records; DCAT-AP names it on Dataset.")], cmp=""),
49: dict(verdict="Keep", line="Keep the property; align values where standards exist: verbatim to prov:Quotation, translated to bibo:translationOf, llm_drafted to IPTC 'Created using Generative AI' (as schema:digitalSourceType does).",
  cands=[(P+"Quotation","related","Covers verbatim only."),
         (P+"Revision","related","Covers revised versions only."),
         ("http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia","related","Value alignment for llm_drafted; schema.org references this code list."),
         (SC+"digitalSourceType","related","schema.org property for IPTC codes, on creative works.")], cmp=""),
50: dict(verdict="Drop", line="A boolean shortcut for a review activity; use the item 9 pattern (a review activity that prov:used the item).",
  cands=[(P+"used","exact","The review activity used the item."),
         (SC+"reviewedBy","related","WebPage only.")], cmp=""),
51: dict(verdict="Keep", line="The verification grade has no standard home; PROV can say a check happened, not its grade.",
  cands=[("https://w3id.org/dpv#VerifiedData","related","Data accuracy, not source verification."),
         ("http://www.w3.org/ns/dqv#QualityAnnotation","related","Could carry a grade as an annotation; heavier.")], cmp=""),
52: dict(verdict="Keep under standard super", line="Declare oht:reviewDue rdfs:subPropertyOf dcterms:date.",
  cands=[(D+"date","super","A date in the record's lifecycle."),
         (SC+"lastReviewed","related","The past review, not the next."),
         (SC+"expires","irrelevant","Content expiry, a different meaning.")], cmp=""),
53: dict(verdict="Keep", line="The library's own reason for holding a record.",
  cands=[(S+"editorialNote","related","Prose; the value is a filterable category.")], cmp=""),
54: dict(verdict="Drop", line="Duplicates the path through the review.",
  cands=[(D+"type","irrelevant","Not needed once dropped.")], cmp=""),
55: dict(verdict="Drop", line="With item 8, the annotation points at the record with oa:hasTarget.",
  cands=[(OA+"hasTarget","exact","'The relationship between an Annotation and its Target.'")], cmp=""),
56: dict(verdict="Replace", line="Record the resolution as a reply annotation (oa:replying) whose body is the resolution text.",
  cands=[(OA+"replying","exact","Motivation for the reply."),
         (OA+"hasBody","exact","The resolution text."),
         (S+"historyNote","related","About past concept states.")], cmp=""),
57: dict(verdict="Replace", line="Use dcat:version on the record state.",
  cands=[(DCAT+"version","exact","A release label; DCAT-AP names it."),
         ("http://purl.org/pav/version","related","Tier 2 alternative."),
         ("http://www.w3.org/2002/07/owl#versionInfo","related","For ontologies.")], cmp=""),
58: dict(verdict="Replace", line="Use dcterms:accessRights with the EU access-right table (PUBLIC, RESTRICTED, NON_PUBLIC), as DCAT-AP does; add an ODRL policy only if redistribution terms need to be precise.",
  cands=[(D+"accessRights","exact","Who may access the archived copy; DCAT-AP harvesters understand it with the EU table."),
         ("http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC","exact","Value."),
         ("http://www.w3.org/ns/odrl/2/distribute","related","The precise action ('To supply the Asset to third-parties') inside an ODRL policy."),
         (D+"license","related","The source's licence; complements.")], cmp=""),
59: dict(verdict="Keep under standard super", line="Declare oht:redactions rdfs:subPropertyOf dcterms:description (or skos:note); dcterms:provenance is about custody, not content edits.",
  cands=[(D+"provenance","related","'changes in ownership and custody'; its usage note allows 'changes successive custodians made', a stretch for redactions."),
         ("https://w3id.org/dpv#DataRedaction","related","A technical measure concept, not a statement."),
         (D+"description","super","Safe parent.")], cmp=""),
60: dict(verdict="Drop", line="The review activity prov:used the record; no forward link needed.",
  cands=[(P+"used","exact","Inverse direction."),
         (SC+"review","related","For schema:Review objects.")], cmp=""),
61: dict(verdict="Replace", line="Use dcterms:type on the review.",
  cands=[(D+"type","exact","One type slot on a review.")], cmp=""),
62: dict(verdict="Replace", line="Type the tool schema:SoftwareSourceCode and give schema:codeRepository a URL to the path in the repository.",
  cands=[(SC+"codeRepository","exact","Link to where the code lives; a path URL within the repository is normal practice, and RO-Crate names the property."),
         ("http://usefulinc.com/ns/doap#repository","related"," Repository object, not a path."),
         (D+"identifier","related","Too general.")], cmp=""),
63: dict(verdict="Keep", line="doap:revision is for software releases; a commit hash on a run has no standard property.",
  cands=[("http://usefulinc.com/ns/doap#revision","related","Domain doap:Version."),
         (D+"identifier","related","Identifies the resource itself, not the code it ran.")], cmp=""),
64: dict(verdict="Drop", line="The session prov:wasAssociatedWith the agent.",
  cands=[(P+"wasAssociatedWith","exact","Inverse direction.")], cmp=""),
65: dict(verdict="Replace", line="Split the two facts: whether a transcript exists (its presence), and its dcterms:accessRights (EU table).",
  cands=[(D+"accessRights","exact","Private versus public."),
         ("http://publications.europa.eu/resource/authority/access-right/PUBLIC","exact","Value.")], cmp=""),
66: dict(verdict="Drop", line="The session prov:generated the transcript.",
  cands=[(P+"generated","exact","Activity to entity it produced."),
         (SC+"transcript","related","Audio and video transcripts.")], cmp=""),
67: dict(verdict="Drop", line="Type the excerpt bibo:Excerpt and link it with prov:wasDerivedFrom to the transcript.",
  cands=[(P+"wasDerivedFrom","exact","Excerpt derived from transcript."),
         ("http://purl.org/ontology/bibo/Excerpt","exact","'A passage selected from a larger work.'"),
         ("http://purl.org/spar/cito/includesExcerptFrom","related","Citation-level."),
         (D+"hasPart","related","The excerpt is redacted, so not simply a part.")], cmp=""),
68: dict(verdict="Replace", line="Use bibo:locator on a part of the transcript, as elsewhere in the graph.",
  cands=[("http://purl.org/ontology/bibo/locator","exact","'A description (often numeric) that locates an item within a containing document'.")], cmp=""),
}
